#In these code email adress is validated using regex expressions. Input csv with Email Address field output df with possible invalid emails
# -*- coding: utf-8 -*-
"""email verification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byt_C71gU3A85PixpDC3cdiKoeA4Yid_
"""

import pandas as pd
df = pd.read_csv("/content/email.csv")
email = df['Email Address']
print(email)

import re
def valid_email(email):
  return bool(re.search(r"^[\w\.\+\-]+\@[\w]+\.[a-z]{2,4}$", email))

lista = []
for element in email:
  if valid_email(element):
    lista.append("True")
  else:
    lista.append("False")

df['is_valid'] = lista
df = df[['Email Address','is_valid']]
df
#df_possible_invalid_emails = df['is_valid'] == False

df_possible_invalid_emails = df[df.is_valid.eq("False")]

df_possible_invalid_emails
